## docker compose -f docker-compose.DEV.yml up --build

services:
  frontend:
    image: node:24-bullseye
    command: sh -c "cp next.config.mjs ./next.config.mjs && npm i && npm run dev"
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - general

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.DEV
    ports:
      - "80:80"
    depends_on:
      frontend:
        condition: service_started
    networks:
      - general

networks:
  general:
    driver: bridge
    name: general
